version: '3'
services:
  rest:
    build: .
    image: activedirectory-microservice
    ports:
      - "80:80"
    environment:
      - ACTIVEDIRECTORY_USERNAME=bindingUsername
      - ACTIVEDIRECTORY_PASSWORD=bindingPassword
      - ACTIVEDIRECTORY_SERVER=domainController.com
      - ACTIVEDIRECTORY_SEARCHBASE=dc=myDomain,dc=myTld