app:
  activedirectory:
    username: x
    password: x
    server: x
    #searchbase: dc=myDomain,dc=myTld
    searchbase: x
  security:
    username: user
    password: password123

micronaut:
  application:
    name: activedirectory
  server:
    port: 8081 # default: -1 (random port)
    cors:
    #  enabled: true # default: false
  router:
    static-resources:
      # YAML file will be available at http://localhost:8080/swagger/greeter-microservice-0.1.0.yml
      # where "greeter-microservice-0.1.0" is derived from the Title and Version attributes of @OpenAPIDefinition
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    # default: false
    enabled: false

jackson:
  serialization:
    indentOutput: true



