app:
  activedirectory:
    username: cn=admin
    password: password
    server: localhost:10389
    #searchbase: dc=myDomain,dc=myTld
    searchbase: dc=root
  security:
    username: SECRET_USERNAME
    password: SECRET_PASSWORD

micronaut:
  application:
    name: activedirectory
  server:
    port: 8080 # default: -1 (random port)
    cors:
    #  enabled: true # default: false
  router:
    static-resources:
      # YAML file will be available at http://localhost:8080/swagger/greeter-microservice-0.1.0.yml
      # where "greeter-microservice-0.1.0" is derived from the Title and Version attributes of @OpenAPIDefinition
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
  security:
    # default: false
    enabled: true

jackson:
  serialization:
    indentOutput: true



